import { db } from "../connections.js";
import bcrypt from 'bcrypt'

export async function up() {
	return new Promise<void>((resolve, reject) => {
		const items = [
			{
				uuid: "uuid-jobpost-1",
				title: 'Job Title',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'c, c++, python, fastify, vanilla JS, sqlite',
				location: 'Heilbronn',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-2",
				title: 'Full-stack developer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'NextJS, FastAPI, docker',
				location: 'Heilbronn',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-3",
				title: 'Software Engineer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Java, Spring Boot, PostgreSQL',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-4",
				title: 'Data Scientist',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Python, Pandas, Machine Learning',
				location: 'Berlin',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-5",
				title: 'DevOps Engineer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'AWS, Docker, Kubernetes',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-6",
				title: 'UX/UI Designer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Figma, Adobe XD, User Research',
				location: 'Munich',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-7",
				title: 'Project Manager',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Agile, Scrum, Communication Skills',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-8",
				title: 'Cybersecurity Analyst',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Network Security, Penetration Testing',
				location: 'Frankfurt',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-9",
				title: 'Mobile App Developer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'React Native, Flutter, iOS, Android',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-10",
				title: 'Cloud Solutions Architect',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Azure, Google Cloud, Architecture Design',
				location: 'Berlin',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-11",
				title: 'Blockchain Developer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Solidity, Ethereum, Smart Contracts',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-12",
				title: 'Game Developer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Unity, C#, Game Design',
				location: 'Hamburg',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-13",
				title: 'SEO Specialist',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'SEO, Google Analytics, Content Strategy',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-14",
				title: 'Content Writer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Content Creation, Blogging, Copywriting',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-15",
				title: 'Network Engineer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Networking, CCNA, Troubleshooting',
				location: 'Stuttgart',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-16",
				title: 'Technical Support Engineer',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Customer Support, Technical Troubleshooting',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-17",
				title: 'Business Analyst',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Data Analysis, Business Intelligence, Reporting',
				location: 'Düsseldorf',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-18",
				title: 'Digital Marketing Manager',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Digital Marketing, Campaign Management, Analytics',
				location: 'Remote',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-19",
				title: 'AI Research Scientist',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'Machine Learning, AI Research, Python',
				location: 'Berlin',
				type: 1,
				job_status: 1,
			},
			{
				uuid: "uuid-jobpost-20",
				title: 'E-commerce Specialist',
				partner_id: "uuid-partner-1",
				description: 'description',
				requirements: 'E-commerce Platforms, Online Sales Strategy',
				location: 'Remote',
				type: 1,
				job_status: 1,
			}
		];

		db.serialize(() => {
			for (const item of items) {
				const uuid = item.uuid || crypto.randomUUID()
				db.run(
					`INSERT INTO jobPosts (id, partner_id, title, description, requirements, location, type, job_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
					[uuid, item.partner_id, item.title, item.description, item.requirements, item.location, item.type, item.job_status],
					(err) => {
						if (err) reject(err);
					}
				);
			}
			resolve();
		});
	});
}
